feat : add-booking
MaXM91/java-shareit pull request #4
Opened 2023-12-03 13:18 UTC by MaXM91

feat : add-booking
- create db,
- create booking
- create comment

2023-12-03 23:30 UTC, NikolaiDem requested changes

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    BookingMapper(@Qualifier("UserServiceImpl") UserService userService,
Маппер выполняет служебную роль преобразования одно объекта в другой. Знаниями только этих объектов он и должен ограничиться. Добавление ему знаний о сервисах создает тесную и ненужную связь с бизнес-логикой, от чего лучше избавиться.

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingDto.getStart().isBefore(LocalDateTime.now())) {
Вместо кастомной валидации можно использовать     
@FutureOrPresent в dto

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
13) Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты.

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Для статусов лучше создать enum и использовать его. Enum легче отслеживать и изменять в коде

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (foundedBooking.getStatus() == StatusBooking.APPROVED) {
Нужно проверить, что статус и не Rejected

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Optional<Booking> foundedBooking = bookingStorage.findById(bookingId);
С Optional хорошей практикой является использование "chain" стиля:

        return bookingStorage.findById(bookingId)
                .orElseThrow(() -> new ObjectNotFoundException("booking id - " + bookingId + " not found"));

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (o1.getEnd().isEqual(o2.getEnd()))
Кодстайл: добавить скобки {} в if/else

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        return o1.getEnd().compareTo(o2.getEnd());
В чем мотивация использовать compareTo, если isEqual возвращает true?

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/BookingForItemDto.java
> +    public BookingForItemDto(Integer id, Integer bookerId, LocalDateTime start, LocalDateTime end) {
Можно использовать @AllArgsConstructor

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(int id, String name, String description, Boolean available) {
Можно использовать @AllArgsConstructor

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemWithBookingDto.java
> +    public ItemWithBookingDto(int id, String name, String description, Boolean available,
Можно использовать @AllArgsConstructor

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @OneToOne
Почему OneToOne?

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    void getBookingByUserIdAndItemId(int userId, int itemId);
Метод с названием get должен что-то возвращать.
И этот метод должен находиться в CommentService

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    CommentMapper commentMapper,
Не используется

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<Item> foundItem = itemStorage.findById(itemId);
Лучше использовать "chain" стиль

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            response.add(foundBookingForItem(item));
Проблема N+1 запроса. Необходимо избавиться от обращения к БД при итерировании по каждому item-у (при получении последнего и следующего бронирований). Допустимо делать несколько запросов, но для всего списка item-ов сразу. Например, одним запросом получить все последние бронирования для списка item-ов. Еще одним одним запросом получить все следующие бронирования и тд. Но не обращаться по каждому item-у в БД

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (int i = 0; i < foundedBooking.size(); i++) {
Логика переусложнена.
Есть хорошие вопросы для написания качественных методов. Нужно ответить на 3 вопроса после написания метода и желательно получить ответы "да".
1) Насколько сложно было написать код?
2) Насколько сложно его понять?
3) Насколько сложно его изменить?

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    default User getUserEntityById(int userId) {
Почему все методы дефолтные?

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/validation/ErrorHandler.java
> +        log.info(methods[3].getClassName() + "/" + methods[2].getMethodName() + ": " + message);
Хорошей практикой логирования исключений является использование:
        log.error(message, exception);

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/validation/ErrorHandler.java
>      private void getLog(StackTraceElement[] methods, String message) {
Метод get... должен что-то возвращать

2023-12-03 23:30 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            } else {
Вся ветка else легко заменяется 2 строчками steam-а : все foundedBooking отсортировать и найти самый близкий к thisMoment

2023-12-04 07:33 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    BookingMapper(@Qualifier("UserServiceImpl") UserService userService,
Выполнено

2023-12-04 08:05 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingDto.getStart().isBefore(LocalDateTime.now())) {
Исправлено

2023-12-04 09:22 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Optional<Booking> foundedBooking = bookingStorage.findById(bookingId);
Исправлено

2023-12-04 09:32 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    if (o1.getEnd().isEqual(o2.getEnd()))
Исправлено

2023-12-04 09:33 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        return o1.getEnd().compareTo(o2.getEnd());
Исправлено, "...return 0;"

2023-12-04 09:38 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/dto/BookingForItemDto.java
> +    public BookingForItemDto(Integer id, Integer bookerId, LocalDateTime start, LocalDateTime end) {
Исправлено

2023-12-04 09:38 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public ItemDto(int id, String name, String description, Boolean available) {
Исправлено

2023-12-04 10:20 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @OneToOne
Исправлено на "@ManyToOne"

2023-12-04 10:27 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    void getBookingByUserIdAndItemId(int userId, int itemId);
Исправлено на "checkBookingByUserIdAndItemId"

2023-12-04 10:40 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    CommentMapper commentMapper,
"CommentMapper" исключено

2023-12-04 10:42 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<Item> foundItem = itemStorage.findById(itemId);
Исправлено

2023-12-04 10:43 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/dto/ItemWithBookingDto.java
> +    public ItemWithBookingDto(int id, String name, String description, Boolean available,
Исправлено

2023-12-05 03:24 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Исправлено

2023-12-05 04:07 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (foundedBooking.getStatus() == StatusBooking.APPROVED) {
Исправлено

2023-12-05 04:12 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    default User getUserEntityById(int userId) {
Исправлено

2023-12-05 08:07 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/validation/ErrorHandler.java
>      private void getLog(StackTraceElement[] methods, String message) {
исправлено на "writeLog"

2023-12-05 09:08 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
Добавлена проверка
@/Query(value = "SELECT * " +
           "FROM bookings AS b " +
           "LEFT OUTER JOIN items AS i ON b.item_id = i.id " +
           "LEFT OUTER JOIN users AS u ON b.booker_id = u.id " +
           "WHERE i.id = :id AND CAST(b.start_date AS date) BETWEEN :start AND :end OR " +
            "     i.id = :id AND CAST(b.end_date AS date) BETWEEN :start AND :end",
            nativeQuery = true)
    List<Booking> checkFreeDateBooking(@/Param("id") int itemId,
                                       @/Param("start") LocalDateTime start,
                                       @/Param("end") LocalDateTime end);"

2023-12-06 08:06 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (int i = 0; i < foundedBooking.size(); i++) {
Исправлено с применением stream()

2023-12-06 08:06 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            } else {
Исправлено с применением stream()

2023-12-06 08:24 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/validation/ErrorHandler.java
> +        log.info(methods[3].getClassName() + "/" + methods[2].getMethodName() + ": " + message);
Исправлено, лишние методы исключены

2023-12-06 21:07 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            response.add(foundBookingForItem(item));
Добавлен метод в репозиторий по выгрузке всех букингов по владельцу вещи, далее через сортировку отправляются на определение прошлого и следующего.

2023-12-07 06:00 UTC, NikolaiDem approved these changes

2023-12-07 06:00 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .collect(Collectors.toList());
Проще применить findFirst().orElse(...) вместо сохранения вы коллекцию.
Аналогично для lastBooking.

2023-12-07 10:50 UTC, merged