feat : add-itemRequest
MaXM91/java-shareit pull request #8
Opened 2023-12-29 01:47 UTC by MaXM91

feat : add-itemRequest
- add controllers test,
- add service test,
- add storage test,
- add more tests;

2023-12-30 06:50 UTC, NikolaiDem requested changes

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestPageableDto.java
> +public interface BookingRequestPageableDto {
Используется?

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/ItemBookingPageableDto.java
> +public interface ItemBookingPageableDto {
Используется?

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    .skip(from)
Вместо кастомной пагинации лучше использовать PagingAndSortingRepository

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +            "WHERE i.id = :id AND CAST(b.start_date AS date) >= :start AND CAST(b.start_date AS date) <= :end OR" +
Пусть существуют 2 бронирования (единицы измерения дни)
1) 1 - 5 
2) 10 - 15
Хотим добавить новое бронирование 8 - 17, сработает ли валидация?

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +            newComment.setId(0);
Для чего устанавливается дефолтное значение?

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            foundedItem.setLastBooking(lastBooking);
А до вызова setLastBooking какой объект находится на месте lastBooking?
Нужна ли эта проверека на null?
Аналогично для nextBooking

2023-12-30 06:50 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private List<Item> items;
N+1 problem
Реализация получения items в ItemRequest аналогично получению bookings в Item

2023-12-30 06:50 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/services/CommentServiceTest.java
> +public class CommentServiceTest {
Еще необходимы интеграционные тесты по каждой фиче

2024-01-07 17:20 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            foundedItem.setLastBooking(lastBooking);
Исправлено. Была ошибка когда приходил null список для обработки. выдавало 500 ошибку. Менял код и прописывал проверки. Сейчас проверку убрал. Проверяю только список на null перед передачей под stream().

2024-01-07 17:37 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestPageableDto.java
> +public interface BookingRequestPageableDto {
Удалено.

2024-01-07 17:37 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/dto/ItemBookingPageableDto.java
> +public interface ItemBookingPageableDto {
Удалено.

2024-01-07 17:40 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    .skip(from)
Исправлено для Booking, Item, ItemRequest.

2024-01-07 18:14 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/booking/storage/BookingStorage.java
> +            "WHERE i.id = :id AND CAST(b.start_date AS date) >= :start AND CAST(b.start_date AS date) <= :end OR" +
Исправлено.

2024-01-09 16:34 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    private List<Item> items;
Исправлено.

2024-01-11 19:15 UTC, MaXM91 commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +            newComment.setId(0);
Для преобразований, когда не определился со всем что нужно. Исправлено.

2024-01-11 19:16 UTC, MaXM91 commented on src/test/java/ru/practicum/shareit/services/CommentServiceTest.java
> +public class CommentServiceTest {
Добавлено.

2024-01-14 21:57 UTC, merged